# Your genome assembly
assembly: ""
# related proteins
proteins: false
# proteins from this organism
proteins_targeted: false
# pre-assembled transcripts/ESTs
transcripts: false
# repeats in FASTA format
rm_lib: false
# Taxonomic group for repeat-masking
rm_species: false
# Path to RNA-seq data
reads: false
# Related genoems and their annotations
references: false
# AUGUSTUS profile
aug_species: "human"
# AUGUSTUS additional options
aug_options: "--singlestrand=true --alternatives-from-evidence=on --minexonintronprob=0.08 --minmeanexonintronprob=0.4 --maxtracks=3"
# Protein aligner profile
spaln_taxon: false
# Search for ncRNAs with RFam
ncrna: false
# Reconstruct transcriptome de-novo
trinity: false
# PASA gene build pipeline
pasa: false
# Consensus gene building
evm: false
# Split assembly into sizes of this
npart_size: 200000000
# Largest possible intron
max_intron_size: 50000
# Remove scaffolds smaller than this
min_contig_size: 5000
# Output directory
outdir: "results"
